# Generated by Django 2.1.4 on 2019-04-17 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=64, null=True)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('unit_symbol', models.PositiveSmallIntegerField(choices=[('Volume', ((1, 'Litter'), (2, 'Gallon'))), ('Weight', ((11, 'Kg'), (12, 'Pound'), (13, 'Ton'), (14, 'Ounce'))), ('Area', ((21, 'sq. cm'), (22, 'sq. ft')))], default=1)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ClientRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.PositiveSmallIntegerField(choices=[('Contract', ((1, 'Request Contract'),)), ('Pickup', ((3, 'Pickup'),)), ('Tank', ((5, 'Install Tank'), (7, 'Repair Tank'), (9, 'Return Tank'))), ('Payment', ((11, 'Show Bill'),))], default=3)),
                ('detail', models.CharField(blank=True, max_length=64, null=True)),
                ('required_date', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_request_client', to='companies.Company')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_request_requester', to=settings.AUTH_USER_MODEL)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_request_server', to='companies.Company')),
            ],
        ),
        migrations.CreateModel(
            name='PickupHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('schedule_date', models.DateTimeField(blank=True, null=True)),
                ('complete_date', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('bill_statement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_descriptions', to='calls.BillStatement')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.Restaurant')),
                ('scheduler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduler_list', to=settings.AUTH_USER_MODEL)),
                ('trucker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trucker_list', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'history_list',
            },
        ),
        migrations.CreateModel(
            name='PickupInterval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.PositiveSmallIntegerField(default=28)),
                ('pickup_date', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_interval_client', to='companies.Company')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessingStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Scheduled'), (3, 'Completed'), (5, 'Paid')], default=1)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calls.ClientRequest')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processing_status_by_me', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'processing_status_set',
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_method', models.PositiveSmallIntegerField(choices=[(1, 'Cash'), (3, 'Credit Card'), (5, 'Cheque'), (7, 'Paypal')], default=5)),
                ('net_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tax_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='receipt_images')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_payer', to='companies.OilCollector')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_seller', to='companies.Restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=64)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('unit_symbol', models.PositiveSmallIntegerField(choices=[('Volume', ((1, 'Litter'), (2, 'Gallon'))), ('Weight', ((11, 'Kg'), (12, 'Pound'), (13, 'Ton'), (14, 'Ounce'))), ('Area', ((21, 'sq. cm'), (22, 'sq. ft')))], default=1)),
                ('how_many', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='calls.Receipt')),
            ],
        ),
        migrations.AddField(
            model_name='processingstatus',
            name='statement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processing_status_statement', to='calls.ReceiptStatement'),
        ),
        migrations.AddField(
            model_name='billstatement',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_statement_list', to='calls.Receipt'),
        ),
    ]
