# Generated by Django 2.1.4 on 2019-04-20 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oilcollectcontract',
            name='collector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_list', to='companies.OilCollector'),
        ),
        migrations.AlterField(
            model_name='oilcollectcontract',
            name='referal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='oilcollectcontract',
            name='restaurant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='contract', serialize=False, to='companies.Restaurant'),
        ),
        migrations.AlterField(
            model_name='oilcollectcontract',
            name='tank_size',
            field=models.PositiveSmallIntegerField(choices=[(16, '  4 Gallon (  16 L ) Pail'), (200, ' 55 Gallon ( 200 L ) Drum'), (400, '110 Gallon ( 400 L ) Bin'), (600, '158 Gallon ( 600 L ) Bin'), (800, '211 Gallon ( 800 L ) Bin'), (1000, '264 Gallon (1000 L ) Bin')], default=200),
        ),
    ]
